# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e76d2ac21d4edd84b1c056426212d36a7046be89f59d831218f1b7062734adb4472d26c4b04539cd225c500d33ef484ab3629f2bed8d50c233d30afa8d3ac6c3

test:
  secret_key_base: 3423c884aca17d59ebde3ee08ef671cc614883d66d86f0056748e978b25d488a723ab48eec597ac0264412b919f6598b7215fb11fac4f77e6aa2396708d72c05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
